services:
- type: web
  name: red-flags-frontend-staging
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
  pullRequestPreviewsEnabled: true     # optional
  envVars:
  - key: NODE_ENV
    value: production
